language: bash

services:
  - docker

env:
  - VARNISH_VER=6.0.2 TAGS=6.0,6,latest
  - VARNISH_VER=4.1.10 TAGS=4.1,4

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
